### ISSUE TITLE
echo builtin is giving correct error code first time then 127

### ISSUE THREAD

**Issue by Inuani** [Laendrun/minishell#22]
<img width="217" alt="Screen Shot 2023-02-13 at 10 05 13 PM" src="https://user-images.githubusercontent.com/100168298/218574327-ab5b2784-54d7-4f0d-a0ae-e75bace26091.png">

I checked with the real echo and there is no prob, I was getting crazy because I did not understand where it came from :O

**Comment by Laendrun** [comment]
I think this comes from the exit status of the child process, it probably returns 127, or the g_code is not set correctly each time and that's also a possibility
