### ISSUE TITLE
if we write something directly after the pipe it is not taken into account, the first letter is truncked

### ISSUE THREAD

**Issue by Inuani** [Laendrun/minishell#5]
<img width="231" alt="Screen Shot 2023-02-03 at 2 04 44 PM" src="https://user-images.githubusercontent.com/100168298/216611132-aee23332-ba78-4551-af33-9b3a5d4866d7.png">

**Comment by Laendrun** [comment]
this is probably linked to the problem that a single pipe is taken as a double pipe

**Comment by Laendrun** [comment]
this is definitely linked to #3
